name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        file_name: .env
    - name: Install modules
      run: yarn
    - name: Run tests
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        sh -c 'echo deb http://dl.google.com/linux/chrome/deb/ stable main > /etc/apt/sources.list.d/google.list'
        apt-get update
        apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic xvfb x11-apps imagemagick google-chrome-stable


        npm run test:e2e:chrome
        pkill node
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          file_name: .env
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-todo-appm" #Must be unique in Heroku
          heroku_email: "mustafaozbatman6@gmail.com"
          usedocker: true