name: Deploy

on:
  push:
    branches:
      - main

jobs:
  create-envfile:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        file_name: .env
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        file_name: .env
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          file_name: .env
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-todo-appm" #Must be unique in Heroku
          heroku_email: "mustafaozbatman6@gmail.com"
          usedocker: true